// Data layer for /projects — the site's flagship, "show everything" page.
// The actual media list is generated by scripts/prepare-projects-media.mjs
// from the client's full archive (every photo, every video, no curation)
// into lib/generated/projects-media.json. This file only adds presentation
// metadata (category labels/order, the Interior Design umbrella framing,
// the Featured Walkthroughs pull) on top of that generated data — never
// edit the JSON by hand, regenerate it from projects/ instead.
import manifestRaw from "./generated/projects-media.json";
import { studio, closingCta } from "./content";

export type CategoryId =
  | "interior-design"
  | "modern-bedroom"
  | "front-elevation"
  | "hotel-design"
  | "commercial-projects"
  | "hospital-design"
  | "site-supervision";

export type ProjectMedia =
  | {
      id: string;
      category: CategoryId;
      kind: "image";
      src: string;
      alt: string;
      width: number;
      height: number;
    }
  | {
      id: string;
      category: CategoryId;
      kind: "video";
      src: string;
      poster: string;
      alt: string;
      width: number;
      height: number;
      sizeMB: number;
      featured: boolean;
      featuredOrder?: number;
    };

const manifest = manifestRaw as ProjectMedia[];

export const categoryLabels: Record<CategoryId, string> = {
  "interior-design": "Interior Design",
  "modern-bedroom": "Modern Bedroom",
  "front-elevation": "Front Elevation",
  "hotel-design": "Hotel Design",
  "commercial-projects": "Commercial Projects",
  "hospital-design": "Hospital Design",
  "site-supervision": "Site Supervision",
};

// A short, decorative line per category — client-requested (small, muted,
// paragraph-weight text near a heading, not a headline itself), shown under
// the category filter on /projects and swapped with it.
export const categoryTaglines: Record<CategoryId, string> = {
  "interior-design": "Every room, considered.",
  "modern-bedroom": "Where the day ends well.",
  "front-elevation": "First impression, permanent.",
  "hotel-design": "Hospitality, drawn precisely.",
  "commercial-projects": "Space that sells itself.",
  "hospital-design": "Care, designed in.",
  "site-supervision": "Drawn once. Built right.",
};

// Interior Design leads — it's the default filter and the richest single
// bucket (Modern Kitchen + Walkthroughs + the general interior-design
// folder, which as of 2026-09-11 also absorbed a category that used to
// stand on its own — 54 items total). Modern Bedroom used to be folded in
// here too but got split back out into its own category — the source
// folder was always its own thing on disk, and the client expects it
// filterable as its own thing on the page. Everything else follows roughly
// richest-to-thinnest. A separate category was renamed to "Commercial
// Projects" on 2026-09-11 (category, folder and output paths).
const CATEGORY_ORDER: CategoryId[] = [
  "interior-design",
  "modern-bedroom",
  "front-elevation",
  "hotel-design",
  "commercial-projects",
  "hospital-design",
  "site-supervision",
];

export const defaultCategory: CategoryId = "interior-design";

export const itemsByCategory: Record<CategoryId, ProjectMedia[]> = Object.fromEntries(
  CATEGORY_ORDER.map((id) => [id, manifest.filter((m) => m.category === id)]),
) as Record<CategoryId, ProjectMedia[]>;

export const categories = CATEGORY_ORDER.map((id) => ({
  id,
  label: categoryLabels[id],
  count: itemsByCategory[id].length,
}));

export const totalItemCount = manifest.length;

// The client has said walkthrough videos drive the most conversions — these
// clips also live inside their own category grid (most are part of the
// Interior Design umbrella; a couple are Front Elevation), but get pulled
// out here for the cinematic slider at the top of the page as well. Not a
// duplicate upload: same generated file, two places it's referenced.
//
// Order is explicit (featuredOrder), not "whatever order the manifest
// array happens to be in" — the client has already asked twice to change
// which video leads this slider, and array order is an accident of job
// definition order in prepare-projects-media.mjs, not something anyone
// should have to reverse-engineer to reorder a slide. Lower sorts first;
// items without a featuredOrder keep their relative manifest order and
// sort after every explicitly-ordered item.
export const featuredWalkthroughs = manifest
  .filter((m): m is Extract<ProjectMedia, { kind: "video" }> => m.kind === "video" && m.featured)
  .map((m, i) => ({ m, i }))
  .sort((a, b) => {
    const ao = a.m.featuredOrder ?? Infinity;
    const bo = b.m.featuredOrder ?? Infinity;
    return ao !== bo ? ao - bo : a.i - b.i;
  })
  .map(({ m }) => m);

export const projectsIntro = {
  index: "01",
  label: "The work",
  tagline: studio.tagline,
  heading: "Every project, drawn and built.",
  body: `${totalItemCount} photos and videos, straight from the studio's own archive — every category, nothing left out.`,
};

export const featuredMeta = {
  index: "02",
  label: "Featured walkthroughs",
  heading: "Walk through before you sign off.",
  body: "The single thing that convinces a client fastest: seeing the space move.",
};

export const gridMeta = {
  index: "03",
  label: "Browse by category",
};

// Mid-page nudge between the featured walkthroughs and the category grid —
// deliberately not a numbered section (no DimensionLine/index of its own):
// the client's own observation is that walkthrough videos convert best, so
// this captures that intent right where it peaks instead of letting it
// carry silently into the grid below. Lighter-weight than closingCta below.
export const midPageCta = {
  body: "Like what you see? Start a conversation on WhatsApp",
  cta: "Start on WhatsApp",
};

// This page's own closing CTA, continuing its 01–03 numbering above.
// Heading/body copy comes from the shared closingCta object in content.ts —
// same pattern as lib/about-content.ts's aboutClosing.
export const projectsClosing = {
  index: "04",
  label: closingCta.label,
};
